/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as SubscriptionApplyRouteImport } from './routes/subscription/apply'
import { Route as SubscriptionEditRouteImport } from './routes/subscription/edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as SubscriptionInvoiceInvoiceIdRouteImport } from './routes/subscription/invoice.$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionApplyRoute = SubscriptionApplyRouteImport.update({
  id: '/subscription/apply',
  path: '/subscription/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionEditRoute = SubscriptionEditRouteImport.update({
  id: '/subscription/edit',
  path: '/subscription/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionInvoiceInvoiceIdRoute =
  SubscriptionInvoiceInvoiceIdRouteImport.update({
    id: '/subscription/invoice/$invoiceId',
    path: '/subscription/invoice/$invoiceId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/subscription/apply': typeof SubscriptionApplyRoute
  '/subscription/edit': typeof SubscriptionEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subscription/invoice/$invoiceId': typeof SubscriptionInvoiceInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/subscription/apply': typeof SubscriptionApplyRoute
  '/subscription/edit': typeof SubscriptionEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subscription/invoice/$invoiceId': typeof SubscriptionInvoiceInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/subscription/apply': typeof SubscriptionApplyRoute
  '/subscription/edit': typeof SubscriptionEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/subscription/invoice/$invoiceId': typeof SubscriptionInvoiceInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/subscription/apply'
    | '/subscription/edit'
    | '/api/auth/$'
    | '/subscription/invoice/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/subscription/apply'
    | '/subscription/edit'
    | '/api/auth/$'
    | '/subscription/invoice/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/subscription/apply'
    | '/subscription/edit'
    | '/api/auth/$'
    | '/subscription/invoice/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  SubscriptionApplyRoute: typeof SubscriptionApplyRoute
  SubscriptionEditRoute: typeof SubscriptionEditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SubscriptionInvoiceInvoiceIdRoute: typeof SubscriptionInvoiceInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/apply': {
      id: '/subscription/apply'
      path: '/subscription/apply'
      fullPath: '/subscription/apply'
      preLoaderRoute: typeof SubscriptionApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/edit': {
      id: '/subscription/edit'
      path: '/subscription/edit'
      fullPath: '/subscription/edit'
      preLoaderRoute: typeof SubscriptionEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/invoice/$invoiceId': {
      id: '/subscription/invoice/$invoiceId'
      path: '/subscription/invoice/$invoiceId'
      fullPath: '/subscription/invoice/$invoiceId'
      preLoaderRoute: typeof SubscriptionInvoiceInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  SubscriptionApplyRoute: SubscriptionApplyRoute,
  SubscriptionEditRoute: SubscriptionEditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SubscriptionInvoiceInvoiceIdRoute: SubscriptionInvoiceInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
