/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountSettingRouteImport } from './routes/account/setting'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as BillingListRouteImport } from './routes/billing/list'
import { Route as SubscriptionApplyRouteImport } from './routes/subscription/apply'
import { Route as SubscriptionEditRouteImport } from './routes/subscription/edit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingRoute = AccountSettingRouteImport.update({
  id: '/account/setting',
  path: '/account/setting',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingListRoute = BillingListRouteImport.update({
  id: '/billing/list',
  path: '/billing/list',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionApplyRoute = SubscriptionApplyRouteImport.update({
  id: '/subscription/apply',
  path: '/subscription/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionEditRoute = SubscriptionEditRouteImport.update({
  id: '/subscription/edit',
  path: '/subscription/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account/setting': typeof AccountSettingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/list': typeof BillingListRoute
  '/subscription/apply': typeof SubscriptionApplyRoute
  '/subscription/edit': typeof SubscriptionEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account/setting': typeof AccountSettingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/list': typeof BillingListRoute
  '/subscription/apply': typeof SubscriptionApplyRoute
  '/subscription/edit': typeof SubscriptionEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account/setting': typeof AccountSettingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/billing/list': typeof BillingListRoute
  '/subscription/apply': typeof SubscriptionApplyRoute
  '/subscription/edit': typeof SubscriptionEditRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account/setting'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/list'
    | '/subscription/apply'
    | '/subscription/edit'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account/setting'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/list'
    | '/subscription/apply'
    | '/subscription/edit'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account/setting'
    | '/auth/login'
    | '/auth/signup'
    | '/billing/list'
    | '/subscription/apply'
    | '/subscription/edit'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountSettingRoute: typeof AccountSettingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  BillingListRoute: typeof BillingListRoute
  SubscriptionApplyRoute: typeof SubscriptionApplyRoute
  SubscriptionEditRoute: typeof SubscriptionEditRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/setting': {
      id: '/account/setting'
      path: '/account/setting'
      fullPath: '/account/setting'
      preLoaderRoute: typeof AccountSettingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/list': {
      id: '/billing/list'
      path: '/billing/list'
      fullPath: '/billing/list'
      preLoaderRoute: typeof BillingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/apply': {
      id: '/subscription/apply'
      path: '/subscription/apply'
      fullPath: '/subscription/apply'
      preLoaderRoute: typeof SubscriptionApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/edit': {
      id: '/subscription/edit'
      path: '/subscription/edit'
      fullPath: '/subscription/edit'
      preLoaderRoute: typeof SubscriptionEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountSettingRoute: AccountSettingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  BillingListRoute: BillingListRoute,
  SubscriptionApplyRoute: SubscriptionApplyRoute,
  SubscriptionEditRoute: SubscriptionEditRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
